DELIMITER $$
CREATE TRIGGER T_COMPETITION_CPT_Check_Organisateur BEFORE INSERT ON T_COMPETITION_CPT FOR EACH ROW BEGIN DECLARE v_role_nom VARCHAR(64); SELECT R.ROL_Nom INTO v_role_nom FROM T_UTILISATEUR_UTL U INNER JOIN T_ROLE_ROL R ON U.ROL_Id = R.ROL_Id WHERE U.UTL_Id = NEW.UTL_Id; IF v_role_nom <> 'Organisateur' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Erreur : L''utilisateur assigné à la compétition doit avoir le rôle Organisateur.'; END IF; END$$

CREATE TRIGGER T_COMPETITION_CPT_Check_Organisateur_Update BEFORE UPDATE ON T_COMPETITION_CPT FOR EACH ROW BEGIN DECLARE v_role_nom VARCHAR(64); IF NEW.UTL_Id <> OLD.UTL_Id THEN SELECT R.ROL_Nom INTO v_role_nom FROM T_UTILISATEUR_UTL U INNER JOIN T_ROLE_ROL R ON U.ROL_Id = R.ROL_Id WHERE U.UTL_Id = NEW.UTL_Id; IF v_role_nom <> 'Organisateur' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Erreur : Le nouvel organisateur doit avoir le rôle Organisateur.'; END IF; END IF; END$$ 
DELIMITER ;

alter TABLE T_MATCH_MTC ADD CONSTRAINT CH_Equipe CHECK (T_MATCH_MTC.EQP_Id <> T_MATCH_MTC.EQP_ID_EquipeB);



alter table T_COMPETITION_CPT
add CONSTRAINT CHECK_DATE CHECK(T_COMPETITION_CPT.CPT_DateDebut<= T_COMPETITION_CPT.CPT_DateFin);

alter TABLE T_STATUTSMATCH_STM ADD CONSTRAINT STM_Unique_Nom UNIQUE (STM_Nom); 

ALTER TABLE T_STATUTEQUIPE_SEQ ADD CONSTRAINT SEQ_Unique_Nom UNIQUE (SEQ_Etat); 
ALTER TABLE T_ROLE_ROL ADD CONSTRAINT ROL_Unique_Nom UNIQUE (ROL_Nom);

ALTER TABLE T_COMPETITION_CPT ADD CONSTRAINT CPT_Unique_Nom UNIQUE (CPT_Nom);
ALTER TABLE T_UTILISATEUR_UTL ADD CONSTRAINT UTL_Unique_Mail UNIQUE (UTL_Mail);
ALTER TABLE T_EQUIPE_EQP ADD CONSTRAINT EQP_Unique_Nom UNIQUE (EQP_Nom,CPT_Id);
alter TABLE T_MATCH_MTC ADD CONSTRAINT STM_Unique_Match UNIQUE (CPT_Id,EQP_Id_EquipeB ,EQP_Id); 
DELIMITER $$
CREATE OR REPLACE TRIGGER T_Match_Verif_Compet 
BEFORE INSERT ON T_MATCH_MTC
fOR EACH ROW
BEGIN
	DECLARE Id_Competition_Equipe_A INT;
    DECLARE Id_Competition_Equipe_b INT;
 	SELECT CPT_Id INTO Id_Competition_Equipe_A FROM T_EQUIPE_EQP WHERE EQP_Id = NEW.EQP_Id;
    SELECT CPT_Id INTO Id_Competition_Equipe_b FROM T_EQUIPE_EQP WHERE EQP_Id = NEW.EQP_Id_EquipeB;
    IF Id_Competition_Equipe_A <> NEW.CPT_Id OR  Id_Competition_Equipe_b <> NEW.CPT_Id THEN 
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Erreur : Une des equipes renseigné ne fait pas partie de la competition'; 
END IF; 
END$$

DELIMITER $$
CREATE OR REPLACE TRIGGER SuppressionCompetition
BEFORE DELETE ON T_COMPETITION_CPT
FOR EACH ROW
BEGIN
    DELETE FROM T_MATCH_MTC WHERE T_MATCH_MTC.CPT_Id = OLD.CPT_Id;
    DELETE FROM T_EQUIPE_EQP WHERE T_EQUIPE_EQP.CPT_Id = OLD.CPT_Id;
END$$

DELIMITER $$
CREATE TRIGGER `SuppressionUtilisateur` BEFORE DELETE ON T_UTILISATEUR_UTL
 FOR EACH ROW BEGIN
    DELETE FROM T_EQUIPE_EQP WHERE T_EQUIPE_EQP.UTL_Id = OLD.UTL_Id;
    DELETE FROM T_COMPETITION_CPT WHERE T_COMPETITION_CPT.UTL_Id = OLD.UTL_Id;
END$$
